"""Shared test fixtures for PrintForge backend tests."""

import asyncio
import os
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

# Force test data directory to a temp location so tests never touch real data
os.environ["PRINTFORGE_DATA_DIR"] = tempfile.mkdtemp(prefix="pf_test_")
os.environ["PRINTFORGE_GCODE_DIR"] = tempfile.mkdtemp(prefix="pf_gcode_")


@pytest.fixture
def tmp_gcode_dir(tmp_path):
    """Provide a temporary directory for G-code files."""
    gcode_dir = tmp_path / "gcodes"
    gcode_dir.mkdir()
    return gcode_dir


@pytest.fixture
def sample_gcode_file(tmp_gcode_dir):
    """Create a minimal G-code file for testing."""
    filepath = tmp_gcode_dir / "test_print.gcode"
    filepath.write_text(
        "; generated by PrusaSlicer 2.7.0\n"
        "; estimated printing time = 30m 15s\n"
        "; filament used [mm] = 2500.0\n"
        "; filament used [g] = 7.5\n"
        ";LAYER:0\n"
        "G28\n"
        "M104 S210\n"
        "M140 S60\n"
        "G1 X10 Y10 Z0.2 F3000\n"
        "G1 X20 Y20 E1.0\n"
        ";LAYER:1\n"
        "G1 Z0.4\n"
        "G1 X30 Y30 E2.5\n"
        ";LAYER:2\n"
        "G1 Z0.6\n"
        "G1 X40 Y40 E4.0\n"
        "M84\n"
    )
    return filepath


@pytest.fixture
def mock_command_queue():
    """Create a mock CommandQueue for GcodeSender tests."""
    queue = MagicMock()
    queue.enqueue = AsyncMock(return_value=asyncio.Future())
    queue.pause = MagicMock()
    queue.resume = MagicMock()
    queue.clear = AsyncMock()
    return queue
