"""Tests for G-code metadata parsing."""

import tempfile
from pathlib import Path

import pytest

from app.printer.gcode_parser import parse_gcode_file, parse_time_string


class TestParseTimeString:
    def test_seconds_only(self):
        assert parse_time_string("5015") == 5015.0

    def test_hms_format(self):
        assert parse_time_string("1h 23m 45s") == 5025.0

    def test_hm_format(self):
        assert parse_time_string("2h 30m") == 9000.0

    def test_with_days(self):
        assert parse_time_string("1d 2h 30m") == 95400.0


class TestParseGcodeFile:
    def test_basic_metadata(self):
        content = """; generated by PrusaSlicer 2.7.0
; estimated printing time = 1h 23m 45s
; filament used [mm] = 5432.1
; filament used [g] = 16.2
;LAYER:0
G28
M104 S210
M140 S60
G1 X10 Y10 Z0.2 F3000
;LAYER:1
G1 X20 Y20 E1.0
;LAYER:2
G1 X30 Y30 E2.0
"""
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".gcode", delete=False
        ) as f:
            f.write(content)
            f.flush()
            filepath = Path(f.name)

        try:
            meta = parse_gcode_file(filepath)
            assert meta.slicer == "PrusaSlicer 2.7.0"
            assert meta.estimated_time_seconds == 5025.0
            assert meta.filament_used_mm == 5432.1
            assert meta.filament_used_grams == 16.2
            assert meta.layer_count == 3
            assert meta.nozzle_temp == 210.0
            assert meta.bed_temp == 60.0
            assert meta.printable_lines > 0
        finally:
            filepath.unlink()

    def test_cura_format(self):
        content = """;Generated with Cura_SteamEngine 5.6.0
;TIME:5015
;Filament used: 1.234m
;LAYER:0
G28
"""
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".gcode", delete=False
        ) as f:
            f.write(content)
            f.flush()
            filepath = Path(f.name)

        try:
            meta = parse_gcode_file(filepath)
            assert meta.estimated_time_seconds == 5015.0
            assert abs(meta.filament_used_mm - 1234.0) < 1.0
        finally:
            filepath.unlink()
