"""G-code file metadata parser.

Extracts useful information from G-code files on upload:
estimated print time, filament usage, layer count, slicer info.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# Cache parsed metadata keyed by (path, mtime, size) to avoid re-reading
# files on every listing. Files don't change after upload so this is safe.
_metadata_cache: dict[tuple[str, float, int], "GcodeMetadata"] = {}
_CACHE_MAX = 100


@dataclass
class GcodeMetadata:
    filename: str
    file_size: int  # bytes
    total_lines: int
    printable_lines: int
    estimated_time_seconds: Optional[float] = None
    filament_used_mm: Optional[float] = None
    filament_used_grams: Optional[float] = None
    layer_count: int = 0
    slicer: Optional[str] = None
    nozzle_temp: Optional[float] = None
    bed_temp: Optional[float] = None
    # Build volume used
    min_x: Optional[float] = None
    max_x: Optional[float] = None
    min_y: Optional[float] = None
    max_y: Optional[float] = None
    max_z: Optional[float] = None

    def to_dict(self) -> dict:
        return {
            "filename": self.filename,
            "fileSize": self.file_size,
            "totalLines": self.total_lines,
            "printableLines": self.printable_lines,
            "estimatedTime": self.estimated_time_seconds,
            "filamentUsedMm": self.filament_used_mm,
            "filamentUsedGrams": self.filament_used_grams,
            "layerCount": self.layer_count,
            "slicer": self.slicer,
            "nozzleTemp": self.nozzle_temp,
            "bedTemp": self.bed_temp,
        }


def calculate_filament_cost(
    filament_mm: float,
    cost_per_kg: float = 18.0,
    density_g_per_cm3: float = 1.24,
    diameter_mm: float = 1.75,
) -> float:
    """Calculate filament cost from length in mm.

    Args:
        filament_mm: Length of filament used in mm.
        cost_per_kg: Cost per kilogram of filament.
        density_g_per_cm3: Filament density (PLA ~1.24, PETG ~1.27, ABS ~1.04).
        diameter_mm: Filament diameter in mm (1.75 or 2.85).

    Returns:
        Estimated cost in the same currency as cost_per_kg.
    """
    import math

    radius_mm = diameter_mm / 2.0
    cross_section_mm2 = math.pi * radius_mm * radius_mm
    volume_mm3 = cross_section_mm2 * filament_mm
    volume_cm3 = volume_mm3 / 1000.0
    weight_g = volume_cm3 * density_g_per_cm3
    return round(weight_g / 1000.0 * cost_per_kg, 2)


# Comment patterns from popular slicers
RE_TIME_PRUSASLICER = re.compile(
    r";\s*estimated printing time.*?=\s*(.+)", re.IGNORECASE
)
RE_TIME_CURA = re.compile(r";TIME:(\d+)")
RE_FILAMENT_PRUSASLICER = re.compile(
    r";\s*filament used\s*\[mm\]\s*=\s*([\d.]+)", re.IGNORECASE
)
RE_FILAMENT_CURA = re.compile(r";Filament used:\s*([\d.]+)m")
RE_FILAMENT_GRAMS = re.compile(
    r";\s*filament used\s*\[g\]\s*=\s*([\d.]+)", re.IGNORECASE
)
RE_SLICER = re.compile(
    r";\s*generated by\s+(.+)", re.IGNORECASE
)
# OrcaSlicer embeds authoritative temps in config comments at end of file.
# These always override the M104/M109 extraction (which catches the 150 °C
# preheat-to-prevent-oozing command, not the user's actual print temp).
RE_NOZZLE_TEMP_ORCA = re.compile(
    r";\s*nozzle_temperature\s*=\s*([\d.]+)", re.IGNORECASE
)
RE_BED_TEMP_ORCA = re.compile(
    r";\s*hot_plate_temp\s*=\s*([\d.]+)", re.IGNORECASE
)
RE_LAYER = re.compile(r";(?:LAYER:|LAYER_CHANGE| LAYER:)", re.IGNORECASE)
# Layer count declared in file header — preferred over counting markers
RE_LAYER_COUNT_CURA = re.compile(r";LAYER_COUNT:(\d+)")
RE_LAYER_COUNT_ORCA = re.compile(
    r";\s*total layer number:\s*(\d+)", re.IGNORECASE
)
# OrcaSlicer also writes '; total layers: N' in some versions
RE_LAYER_COUNT_ORCA_ALT = re.compile(
    r";\s*total layers:\s*(\d+)", re.IGNORECASE
)


def parse_time_string(time_str: str) -> float:
    """Parse time strings like '1h 23m 45s' or '5015' (seconds)."""
    time_str = time_str.strip()

    # Pure seconds
    if time_str.isdigit():
        return float(time_str)

    total = 0.0
    # Match hours, minutes, seconds
    h_match = re.search(r"(\d+)\s*h", time_str)
    m_match = re.search(r"(\d+)\s*m", time_str)
    s_match = re.search(r"(\d+)\s*s", time_str)
    if h_match:
        total += int(h_match.group(1)) * 3600
    if m_match:
        total += int(m_match.group(1)) * 60
    if s_match:
        total += int(s_match.group(1))

    # Also try "d" for days
    d_match = re.search(r"(\d+)\s*d", time_str)
    if d_match:
        total += int(d_match.group(1)) * 86400

    return total if total > 0 else 0.0


def parse_gcode_file(filepath: Path) -> GcodeMetadata:
    """Parse a G-code file and extract metadata.

    Results are cached by file path, modification time, and size so that
    repeated calls (e.g. file listings) don't re-read the entire file.
    Only reads comments and counts lines - does not execute anything.
    """
    stat = filepath.stat()
    cache_key = (str(filepath), stat.st_mtime, stat.st_size)

    cached = _metadata_cache.get(cache_key)
    if cached is not None:
        return cached

    metadata = GcodeMetadata(
        filename=filepath.name,
        file_size=stat.st_size,
        total_lines=0,
        printable_lines=0,
    )

    # Layer count declared in the slicer header (more reliable than counting
    # markers; populated by _parse_comment when found).
    header_layer_count = 0

    with open(filepath, "r", errors="replace") as f:
        for line in f:
            metadata.total_lines += 1
            stripped = line.strip()

            if not stripped:
                continue

            # Count layer markers throughout the file as a fallback.
            # If the slicer declared a total in the header, we override this
            # at the end of the scan with the more authoritative value.
            if RE_LAYER.search(stripped):
                metadata.layer_count += 1

            # Parse comments for metadata
            if stripped.startswith(";"):
                hc = _parse_comment(stripped, metadata)
                if hc:
                    header_layer_count = hc
                continue

            # Count printable (non-comment, non-empty) lines
            metadata.printable_lines += 1

            # Extract first temperature commands for display
            if metadata.nozzle_temp is None and stripped.startswith(("M104", "M109")):
                s_match = re.search(r"S([\d.]+)", stripped)
                if s_match:
                    temp = float(s_match.group(1))
                    if temp > 0:
                        metadata.nozzle_temp = temp

            if metadata.bed_temp is None and stripped.startswith(("M140", "M190")):
                s_match = re.search(r"S([\d.]+)", stripped)
                if s_match:
                    temp = float(s_match.group(1))
                    if temp > 0:
                        metadata.bed_temp = temp

    # Header-declared count beats marker counting (more accurate, and avoids
    # counting ;BEFORE_LAYER_CHANGE etc. if RE_LAYER ever widens).
    if header_layer_count > 0:
        metadata.layer_count = header_layer_count

    # Cache result (evict oldest if full)
    if len(_metadata_cache) >= _CACHE_MAX:
        _metadata_cache.pop(next(iter(_metadata_cache)))
    _metadata_cache[cache_key] = metadata

    return metadata


def _parse_comment(line: str, metadata: GcodeMetadata) -> int:
    """Extract metadata from a G-code comment line.

    Returns the header-declared layer count if found, else 0.
    """
    # Estimated time
    match = RE_TIME_PRUSASLICER.search(line)
    if match and metadata.estimated_time_seconds is None:
        metadata.estimated_time_seconds = parse_time_string(match.group(1))

    match = RE_TIME_CURA.search(line)
    if match and metadata.estimated_time_seconds is None:
        metadata.estimated_time_seconds = float(match.group(1))

    # Filament usage
    match = RE_FILAMENT_PRUSASLICER.search(line)
    if match:
        metadata.filament_used_mm = float(match.group(1))

    match = RE_FILAMENT_CURA.search(line)
    if match:
        metadata.filament_used_mm = float(match.group(1)) * 1000  # m to mm

    match = RE_FILAMENT_GRAMS.search(line)
    if match:
        metadata.filament_used_grams = float(match.group(1))

    # Slicer info
    match = RE_SLICER.search(line)
    if match and metadata.slicer is None:
        metadata.slicer = match.group(1).strip()

    # OrcaSlicer temperature config comments (end of file, always authoritative).
    # These override the M104/M109 extraction because OrcaSlicer's embedded
    # start G-code starts with "M104 S150" (preheat to prevent oozing), not
    # the user's actual print temperature.
    match = RE_NOZZLE_TEMP_ORCA.search(line)
    if match:
        temp = float(match.group(1))
        if temp > 0:
            metadata.nozzle_temp = temp

    match = RE_BED_TEMP_ORCA.search(line)
    if match:
        temp = float(match.group(1))
        if temp > 0:
            metadata.bed_temp = temp

    # Layer count declared in header — Cura: ;LAYER_COUNT:N
    # OrcaSlicer: '; total layer number: N' or '; total layers: N'
    match = RE_LAYER_COUNT_CURA.search(line)
    if match:
        return int(match.group(1))
    match = RE_LAYER_COUNT_ORCA.search(line)
    if match:
        return int(match.group(1))
    match = RE_LAYER_COUNT_ORCA_ALT.search(line)
    if match:
        return int(match.group(1))

    return 0
