"""G-code file metadata parser.

Extracts useful information from G-code files on upload:
estimated print time, filament usage, layer count, slicer info.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class GcodeMetadata:
    filename: str
    file_size: int  # bytes
    total_lines: int
    printable_lines: int
    estimated_time_seconds: Optional[float] = None
    filament_used_mm: Optional[float] = None
    filament_used_grams: Optional[float] = None
    layer_count: int = 0
    slicer: Optional[str] = None
    nozzle_temp: Optional[float] = None
    bed_temp: Optional[float] = None
    # Build volume used
    min_x: Optional[float] = None
    max_x: Optional[float] = None
    min_y: Optional[float] = None
    max_y: Optional[float] = None
    max_z: Optional[float] = None

    def to_dict(self) -> dict:
        return {
            "filename": self.filename,
            "fileSize": self.file_size,
            "totalLines": self.total_lines,
            "printableLines": self.printable_lines,
            "estimatedTime": self.estimated_time_seconds,
            "filamentUsedMm": self.filament_used_mm,
            "filamentUsedGrams": self.filament_used_grams,
            "layerCount": self.layer_count,
            "slicer": self.slicer,
            "nozzleTemp": self.nozzle_temp,
            "bedTemp": self.bed_temp,
        }


# Comment patterns from popular slicers
RE_TIME_PRUSASLICER = re.compile(
    r";\s*estimated printing time.*?=\s*(.+)", re.IGNORECASE
)
RE_TIME_CURA = re.compile(r";TIME:(\d+)")
RE_FILAMENT_PRUSASLICER = re.compile(
    r";\s*filament used\s*\[mm\]\s*=\s*([\d.]+)", re.IGNORECASE
)
RE_FILAMENT_CURA = re.compile(r";Filament used:\s*([\d.]+)m")
RE_FILAMENT_GRAMS = re.compile(
    r";\s*filament used\s*\[g\]\s*=\s*([\d.]+)", re.IGNORECASE
)
RE_SLICER = re.compile(
    r";\s*generated by\s+(.+)", re.IGNORECASE
)
RE_LAYER = re.compile(r";(?:LAYER:|LAYER_CHANGE| LAYER:)", re.IGNORECASE)


def parse_time_string(time_str: str) -> float:
    """Parse time strings like '1h 23m 45s' or '5015' (seconds)."""
    time_str = time_str.strip()

    # Pure seconds
    if time_str.isdigit():
        return float(time_str)

    total = 0.0
    # Match hours, minutes, seconds
    h_match = re.search(r"(\d+)\s*h", time_str)
    m_match = re.search(r"(\d+)\s*m", time_str)
    s_match = re.search(r"(\d+)\s*s", time_str)
    if h_match:
        total += int(h_match.group(1)) * 3600
    if m_match:
        total += int(m_match.group(1)) * 60
    if s_match:
        total += int(s_match.group(1))

    # Also try "d" for days
    d_match = re.search(r"(\d+)\s*d", time_str)
    if d_match:
        total += int(d_match.group(1)) * 86400

    return total if total > 0 else 0.0


def parse_gcode_file(filepath: Path) -> GcodeMetadata:
    """Parse a G-code file and extract metadata.

    Only reads comments and counts lines - does not execute anything.
    """
    metadata = GcodeMetadata(
        filename=filepath.name,
        file_size=filepath.stat().st_size,
        total_lines=0,
        printable_lines=0,
    )

    with open(filepath, "r", errors="replace") as f:
        for line in f:
            metadata.total_lines += 1
            stripped = line.strip()

            if not stripped:
                continue

            # Count layers
            if RE_LAYER.search(stripped):
                metadata.layer_count += 1

            # Parse comments for metadata
            if stripped.startswith(";"):
                _parse_comment(stripped, metadata)
                continue

            # Count printable (non-comment, non-empty) lines
            metadata.printable_lines += 1

            # Extract first temperature commands for display
            if metadata.nozzle_temp is None and stripped.startswith(("M104", "M109")):
                s_match = re.search(r"S([\d.]+)", stripped)
                if s_match:
                    temp = float(s_match.group(1))
                    if temp > 0:
                        metadata.nozzle_temp = temp

            if metadata.bed_temp is None and stripped.startswith(("M140", "M190")):
                s_match = re.search(r"S([\d.]+)", stripped)
                if s_match:
                    temp = float(s_match.group(1))
                    if temp > 0:
                        metadata.bed_temp = temp

    return metadata


def _parse_comment(line: str, metadata: GcodeMetadata) -> None:
    """Extract metadata from a G-code comment line."""
    # Estimated time
    match = RE_TIME_PRUSASLICER.search(line)
    if match and metadata.estimated_time_seconds is None:
        metadata.estimated_time_seconds = parse_time_string(match.group(1))

    match = RE_TIME_CURA.search(line)
    if match and metadata.estimated_time_seconds is None:
        metadata.estimated_time_seconds = float(match.group(1))

    # Filament usage
    match = RE_FILAMENT_PRUSASLICER.search(line)
    if match:
        metadata.filament_used_mm = float(match.group(1))

    match = RE_FILAMENT_CURA.search(line)
    if match:
        metadata.filament_used_mm = float(match.group(1)) * 1000  # m to mm

    match = RE_FILAMENT_GRAMS.search(line)
    if match:
        metadata.filament_used_grams = float(match.group(1))

    # Slicer info
    match = RE_SLICER.search(line)
    if match and metadata.slicer is None:
        metadata.slicer = match.group(1).strip()
